services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    #    image: plexinc/pms-docker
    container_name: plex
    #    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP}
      - ALLOWED_NETWORKS=10.0.0.1/24,172.16.0.0/16
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ./data/plex:/config
      - /dev/shm:/transcode
      - /media/storage/plexMedia/Media/TV Shows:/tv
      - /media/storage/plexMedia/Media/Movies:/movies
      - /media/storage/plexMedia/Media/Home Videos:/home_videos
    restart: unless-stopped

networks:
  default:
    external: true
    name: npm_network
