services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER={pia_user}
      - OPENVPN_PASSWORD={pia_password}
      - SERVER_REGIONS=US East
    ports:
      # Bittorrent 
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
      # Prowlarr
      - 9696:9696
      # Sonarr port
      - 8989:8989
      # Radarr port
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ${DOCKER_DATA_PATH}/plex/qbittorrent/appdata:/config
      - /media/storage/plexMedia/Media:/downloads
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - ${DOCKER_DATA_PATH}/plex/data/prowlarr:/config
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - qbittorrent

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/plex/data/sonarr:/config
      - "/media/storage/plexMedia/Media/TV Shows:/tv"
      - /media/storage/plexMedia/Media:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - prowlarr
      - qbittorrent

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/plex/data/radarr:/config
      - /media/storage/plexMedia/Media/Movies:/movies
      - /media/storage/plexMedia/Media:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - prowlarr
      - qbittorrent

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
#    network_mode: host
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - ${DOCKER_DATA_PATH}/plex/data/tautulli:/config
      - "${DOCKER_DATA_PATH}/plex/data/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs"
    ports:
     - 8181:8181
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
#    image: plexinc/pms-docker
    container_name: plex
#    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - VERSION=docker
      - 'ADVERTISE_IP=http://10.0.0.253:32400/,http://plex.local/'
      - 'ALLOWED_NETWORKS=10.0.0.1/24,172.16.0.0/16'
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${DOCKER_DATA_PATH}/plex/data/plex:/config
      - ${DOCKER_DATA_PATH}/plex/data/plex/transcode:/transcode
      - "/media/storage/plexMedia/Media/TV Shows:/tv"
      - /media/storage/plexMedia/Media/Movies:/movies
      - "/media/storage/plexMedia/Media/Home Videos:/home_videos"
    restart: unless-stopped
