
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PORT=5055 #optional
    volumes:
      - ./data:/app/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: npm_network