
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    network_mode: host
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_DATA_PATH}/overseerr/data:/app/config
    restart: unless-stopped
volumes:
  overseerr:
    external: true
