containers:
  bedrock:
    - name: bds
      # The hostname here is the name of the service in the compose YML.
      ssh: bds:2222
      # itzg writes out the password as yaml to the root of /data
      passwordFile: /bds/.remote-console.yaml
      worlds:
        - "/bds/worlds/Bedrock level"

# Whenever the last player logs out, limited to every 3 hours. Plus at 3AM
schedule:
  onLastLogout: true
  minInterval: 3h
  daily: 03:00
#  startupDelay: 1m

trim:
  trimDays: 2
  keepDays: 14
  minKeep: 2
