services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      SAMBA_VOLUME_CONFIG_sharename: "[media]; path=/shares/media; available = yes;
        browsable = yes; writable = yes; read only = no; force user = ${MEDIA_USER};
        public = yes; guest ok = yes"
    volumes:
      - /media/storage/plexMedia:/shares/media
    ports:
      - 445:445
    env_file: .env
networks: {}
