services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M 
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      BASE_URL: ${BASE_URL}

networks:
  default:
    external: true
    name: npm_network
