services:
  gluetun:
    image: qmcgaw/gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    networks:
      - npm_network
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
    ports:
      - 8081:8081 #qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696 #Prowlarr
      - 8989:8989 #Sonarr
      - 7878:7878 #Radarr
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ./data/qbittorrent/appdata:/config
      - /media/storage/plexMedia/Media:/downloads
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - ./data/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - qbittorrent
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/sonarr:/config
      - /media/storage/plexMedia/Media/TV Shows:/tv
      - /media/storage/plexMedia/Media:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - prowlarr
      - qbittorrent
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/radarr:/config
      - /media/storage/plexMedia/Media/Movies:/movies
      - /media/storage/plexMedia/Media:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - prowlarr
      - qbittorrent
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1001
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - ./data/tautulli:/config
      - ${PLEX_DATA_DIR}/Library/Application Support/Plex Media Server/Logs:/plex_logs
    networks:
      - npm_network
    ports:
      - 8181:8181
    restart: unless-stopped
  profilarr:
    image: santiagosayshey/profilarr:latest # Use :beta for early access to new features
    container_name: profilarr
    networks:
      - npm_network
    ports:
      - 6868:6868
    volumes:
      - ./data/profilarr:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped
networks:
  npm_network:
    external: true
    name: npm_network

x-dockge:
  urls:
    - http://10.0.0.253:8081/
    - http://10.0.0.253:8989/
    - ""
